{:name => "Candidate ID Number", :required=> false},
{:name => "Date Received", :required=> false},
{:name => "Last Revised By", :required=> false},
{:name => "Last Revised Date", :required=> false},
{:name => "Postmark Date", :required=> false},
{:name => "Microfilm Number", :required=> false},
{:name => "Candidate Last Name", :required=> false},
{:name => "Candidate First Name", :required=> false},
{:name => "Candidate Middle Initial", :required=> false},
{:name => "Candidate Phone", :required=> false},
{:name => "Candidate Address", :required=> false},
{:name => "Candidate City", :required=> false},
{:name => "Candidate State", :required=> false},
{:name => "Candidate Zip", :required=> false},
{:name => "County", :required=> false},
{:name => "Title", :required=> false},
{:name => "Agency", :required=> false},
{:name => "Agency Address", :required=> false},
{:name => "Agency Phone", :required=> false},
{:name => "Immediate Supervisor", :required=> false},
{:name => "Supervisor Title", :required=> false},
{:name => "Conflict", :required=> false},
{:name => "Nature of Benefit", :required=> false},
{:name => "Candidate Receive Benefit", :required=> false},
{:name => "Family Receive Benefit", :required=> false},
{:name => "Name of Family Memeber", :required=> false},
{:name => "Business Receive Benefit", :required=> false},
{:name => "Business Name", :required=> false},
{:name => "Member of Legislature Only", :required=> false}