{:name => "Candidate First Name", :required=> false},
{:name => "Candidate Middle Initial", :required=> false},
{:name => "Candidate Last Name", :required=> false},
{:name => "Candidate Address", :required=> false},
{:name => "Candidate City", :required=> false},
{:name => "Candidate State", :required=> false},
{:name => "Candidate Zip", :required=> false},
{:name => "Form CFLA-8 ID Number", :required=> false},
{:name => "Form ID Number", :required=> false},
{:name => "Payee Name", :required=> false},
{:name => "Payee Address", :required=> false},
{:name => "Payee City", :required=> false},
{:name => "Payee State", :required=> false},
{:name => "Expenditure Description", :required=> false},
{:name => "Expenditure Date", :required=> false},
{:name => "Expenditure Cash Amount", :required=> false},
{:name => "Expenditure In-Kind Amount", :required=> false},
{:name => "Total Expenditure", :required=> false}