{:name => "Form ID", :required=> false},
{:name => "Entity ID", :required=> false},
{:name => "Postmark Date", :required=> false},
{:name => "Date Received", :required=> false},
{:name => "Microfilm Number", :required=> false},
{:name => "Permanent Phone", :required=> false},
{:name => "Temporary Address", :required=> false},
{:name => "Temporary City", :required=> false},
{:name => "Temporary State", :required=> false},
{:name => "Temporary Zip", :required=> false},
{:name => "Temporary Phone", :required=> false},
{:name => "Date Last Revised", :required=> false},
{:name => "Last Revised By", :required=> false},
{:name => "Committee ID", :required=> false},
{:name => "Entity Orginzation Name", :required=> false},
{:name => "Entity First Name", :required=> false},
{:name => "Entity Middle Initial", :required=> false},
{:name => "Entity Last Name", :required=> false},
{:name => "Committee Name", :required=> false}