{:name => "Committee Name", :required=> false},
{:name => "Form ID Number", :required=> false},
{:name => "Committe ID Number", :required=> false},
{:name => "Postmark Date", :required=> false},
{:name => "Date Received", :required=> false},
{:name => "Microfilm Number", :required=> false},
{:name => "Agent Name", :required=> false},
{:name => "Agent Address", :required=> false},
{:name => "Agent City", :required=> false},
{:name => "Agent State", :required=> false},
{:name => "Agent Zip", :required=> false},
{:name => "Agent Phone", :required=> false},
{:name => "Contributor Name", :required=> false},
{:name => "Contributor Address", :required=> false},
{:name => "Contributor City", :required=> false},
{:name => "Contributor State", :required=> false},
{:name => "Contributor Zip", :required=> false},
{:name => "Contributor Phone", :required=> false},
{:name => "Contribution Date", :required=> false},
{:name => "Amount Received", :required=> false},
{:name => "Nature", :required=> false},
{:name => "Description of In-Kind", :required=> false},
{:name => "Transfer Date", :required=> false},
{:name => "Transfer Amount", :required=> false},
{:name => "Transfer Nature", :required=> false},
{:name => "Transfer In-Kind Description", :required=> false},
{:name => "Date Last Revised", :required=> false},
{:name => "Last Revised By", :required=> false}