{:name => "Contributor Name", :required=> false},
{:name => "Form B9 ID", :required=> false},
{:name => "Form ID", :required=> false},
{:name => "Recipient ID", :required=> false},
{:name => "Support/Oppose", :required=> false},
{:name => "Nature of Expenditure", :required=> false},
{:name => "Expenditure Date", :required=> false},
{:name => "Previous Total", :required=> false},
{:name => "Amount", :required=> false},
{:name => "Total", :required=> false},
{:name => "Description", :required=> false},
{:name => "Entry Date", :required=> false},
{:name => "Recipient Name", :required=> false}