      {:name => "Candidate First Name", :required=> false},
      {:name => "Candidate Middle Initial", :required=> false},
      {:name => "Candidate Last Name", :required=> false},
      {:name => "Candidate Address", :required=> false},
      {:name => "Candidate City", :required=> false},
      {:name => "Candidate State", :required=> false},
      {:name => "Candidate Zip", :required=> false},
      {:name => "Form ID Number", :required=> false},
      {:name => "Candidate ID", :required=> false},
      {:name => "Postmark Date", :required=> false},
      {:name => "Date Received", :required=> false},
      {:name => "Microfilm Number", :required=> false},
      {:name => "Election Year", :required=> false},
      {:name => "Office Sought", :required=> false},
      {:name => "District", :required=> false},
      {:name => "Candidate Phone", :required=> false},
      {:name => "Last Revised Date", :required=> false},
      {:name => "Last Revised By", :required=> false}