{:name => "Candidate First Name", :required=> false},
{:name => "Candidate Middle Initial", :required=> false},
{:name => "Candidate Last Name", :required=> false},
{:name => "Candidate Address", :required=> false},
{:name => "Candidate City", :required=> false},
{:name => "Candidate State", :required=> false},
{:name => "Candidate Zip", :required=> false},
{:name => "Candidate Committee Name", :required=> false},
{:name => "Committee Phone", :required=> false},
{:name => "Form ID Number", :required=> false},
{:name => "Candidate ID", :required=> false},
{:name => "Committee ID", :required=> false},
{:name => "Postmark Date", :required=> false},
{:name => "Date Received", :required=> false},
{:name => "Microfilm Number", :required=> false},
{:name => "Office Sought", :required=> false},
{:name => "District", :required=> false},
{:name => "Business Address", :required=> false},
{:name => "Business Phone", :required=> false},
{:name => "Home Phone", :required=> false},
{:name => "Expend In Words", :required=> false},
{:name => "Expend In Numbers", :required=> false},
{:name => "Last Revised Date", :required=> false},
{:name => "Last Revised By", :required=> false}