      {:name => "Committee ID", :required=> false},
      {:name => "Date Received", :required=> false},
      {:name => "Committee ID Expenditure is For", :required=> false},
      {:name => "Support/Oppose", :required=> false},
      {:name => "Nature of Expenditure", :required=> false},
      {:name => "Expenditure Date", :required=> false},
      {:name => "Amount", :required=> false},
      {:name => "Description", :required=> false},
      {:name => "Line ID", :required=> false},
      {:name => "Committee Name Expenditure is For", :required=> false}