      {:name => "Candidate First Name", :required=> false},
      {:name => "Candidate Middle Initial", :required=> false},
      {:name => "Candidate Last Name", :required=> false},
      {:name => "Candidate Address", :required=> false},
      {:name => "Candidate City", :required=> false},
      {:name => "Candidate State", :required=> false},
      {:name => "Candidate Zip", :required=> false},
      {:name => "Candidate Committee Name", :required=> false},
      {:name => "Committe Phone", :required=> false},
      {:name => "Form ID Number", :required=> false},
      {:name => "Candidate ID", :required=> false},
      {:name => "Committee ID", :required=> false},
      {:name => "Postmark Date", :required=> false},
      {:name => "Date Received", :required=> false},
      {:name => "Microfilm Number", :required=> false},
      {:name => "Business Address", :required=> false},
      {:name => "Business Phone", :required=> false},
      {:name => "Home Phone", :required=> false},
      {:name => "Treasurer Address", :required=> false},
      {:name => "Treasurer Phone", :required=> false},
      {:name => "Office Sought", :required=> false},
      {:name => "Election Type", :required=> false},
      {:name => "Report Start Date", :required=> false},
      {:name => "Report End Date", :required=> false},
      {:name => "Public Funds On Hand", :required=> false},
      {:name => "Public Funds Received", :required=> false},
      {:name => "Interest Income", :required=> false},
      {:name => "Expenditures of Public Funds", :required=> false},
      {:name => "Balance Of Public Funds", :required=> false},
      {:name => "Last Revised Date", :required=> false},
      {:name => "Last Revised By", :required=> false}