{:name => "ID", :required=> false},
{:name => "Lobbyist Last Name", :required=> false},
{:name => "Lobbyist First Name", :required=> false},
{:name => "Principal Name", :required=> false},
{:name => "Statement Due", :required=> false},
{:name => "Due Date", :required=> false},
{:name => "Date Filed", :required=> false},
{:name => "Amount", :required=> false},
{:name => "Status", :required=> false},
{:name => "Reduced", :required=> false},
{:name => "Order Signed", :required=> false},
{:name => "Date Paid", :required=> false},
{:name => "Interest Paid", :required=> false}
