{:name => "Committee Name", :required=> false},
{:name => "Committee ID", :required=> false},
{:name => "Date Last Revised", :required=> false},
{:name => "Last Revised By", :required=> false},
{:name => "Date Received", :required=> false},
{:name => "Postmark Date", :required=> false},
{:name => "Microfilm Number", :required=> false},
{:name => "Type of Contributor", :required=> false},
{:name => "PAC ID", :required=> false},
{:name => "Description Of Services", :required=> false},
{:name => "PAC Name", :required=> false}