{:name => "ID", :required=> false},
{:name => "Corporation Name", :required=> false},
{:name => "Month Of Contribution", :required=> false},
{:name => "Due Date", :required=> false},
{:name => "Date Filed", :required=> false},
{:name => "Amount", :required=> false},
{:name => "Status", :required=> false},
{:name => "Reduced", :required=> false},
{:name => "Order Signed", :required=> false},
{:name => "Date Paid", :required=> false},
{:name => "Interest Paid", :required=> false}