      {:name => "Form ID Number", :required=> false},
      {:name => "Committee ID", :required=> false},
      {:name => "Date Received", :required=> false},
      {:name => "Committee Expenditure ID", :required=> false},
      {:name => "Support/Oppose", :required=> false},
      {:name => "Nature of Expenditure", :required=> false},
      {:name => "Expenditure Date", :required=> false},
      {:name => "Amount", :required=> false},
      {:name => "Expense Category", :required=> false},
      {:name => "Expenditure Committee Name", :required=> false}