      {:name => "Candiate First Name", :required=> false},
      {:name => "Candidate Middle Initial", :required=> false},
      {:name => "Candidate Last Name", :required=> false},
      {:name => "Candidate Address", :required=> false},
      {:name => "Candidate City", :required=> false},
      {:name => "Candidate State", :required=> false},
      {:name => "Candidate Zip", :required=> false},
      {:name => "Candidate Committee Name", :required=> false},
      {:name => "Committee Phone", :required=> false},
      {:name => "Form CFLA-9 ID", :required=> false},
      {:name => "Form ID Number", :required=> false},
      {:name => "Payee Name", :required=> false},
      {:name => "Payee Address", :required=> false},
      {:name => "Payee City", :required=> false},
      {:name => "Payee State", :required=> false},
      {:name => "Purpose of Expenditure", :required=> false},
      {:name => "Expenditure Date", :required=> false},
      {:name => "Expenditure Amount", :required=> false}