{:name => "Committee Name", :required=> false},
{:name => "Committee Address", :required=> false},
{:name => "Committee Type", :required=> false},
{:name => "Committee City", :required=> false},
{:name => "Committee State", :required=> false},
{:name => "Committee Zip", :required=> false},
{:name => "Committee ID Number", :required=> false},
{:name => "Date Last Revised", :required=> false},
{:name => "Last Revised By", :required=> false},
{:name => "Date Received", :required=> false},
{:name => "Postmark Date", :required=> false},
{:name => "Microfilm Number", :required=> false},
{:name => "Election Date", :required=> false},
{:name => "Type of Filing", :required=> false},
{:name => "Nature of Filing", :required=> false},
{:name => "Additional Ballot Question", :required=> false},
{:name => "Report Start Date", :required=> false},
{:name => "Report End Date", :required=> false},
{:name => "Field 1", :required=> false},
{:name => "Field 2A", :required=> false},
{:name => "Field 2B", :required=> false},
{:name => "Field 2C", :required=> false},
{:name => "Field 3", :required=> false},
{:name => "Field 4A", :required=> false},
{:name => "Field 4B", :required=> false},
{:name => "Field 5", :required=> false},
{:name => "Field 6", :required=> false},
{:name => "Field 7A", :required=> false},
{:name => "Field 7B", :required=> false},
{:name => "Field 7C", :required=> false},
{:name => "Field 7D", :required=> false},
{:name => "Field 8A", :required=> false},
{:name => "Field 8B", :required=> false},
{:name => "Field 8C", :required=> false},
{:name => "Field 8D", :required=> false},
{:name => "Field 9", :required=> false},
{:name => "Field 10", :required=> false},
{:name => "Field 11", :required=> false},
{:name => "Field 12", :required=> false},
{:name => "Field 13", :required=> false},
{:name => "Field 14", :required=> false},
{:name => "Field 15", :required=> false},
{:name => "Field 16", :required=> false},
{:name => "Field 17", :required=> false},
{:name => "Field 18", :required=> false},
{:name => "Field 19", :required=> false},
{:name => "Field 20", :required=> false},
{:name => "Field 21", :required=> false},
{:name => "Field 22", :required=> false},
{:name => "Field 23", :required=> false},
{:name => "Field 23", :required=> false},
{:name => "Field 24", :required=> false},
{:name => "Field 25", :required=> false},
{:name => "Field 26", :required=> false},
{:name => "Field 27", :required=> false},
{:name => "Adjustment", :required=> false},
{:name => "Total Unitemized Bills", :required=> false},
{:name => "Total Unpaid Bills", :required=> false},
{:name => "Total All Bills", :required=> false},
