      {:name => "Document ID", :required=> false},
      {:name => "Year Covered", :required=> false},
      {:name => "First Session", :required=> false},
      {:name => "First Session Year", :required=> false},
      {:name => "Second Session", :required=> false},
      {:name => "Second Session Year", :required=> false},
      {:name => "Compensated", :required=> false},
      {:name => "Compensation", :required=> false},
      {:name => "Lobby Issues", :required=> false},
      {:name => "Industry Description", :required=> false},
      {:name => "Non Industry Description", :required=> false},
      {:name => "Officers", :required=> false},
      {:name => "Employees", :required=> false},
      {:name => "Date Received", :required=> false},
      {:name => "Lobbyist ID", :required=> false},
      {:name => "Lobbyist Name", :required=> false},
      {:name => "Lobbyist Office Address", :required=> false},
      {:name => "Lobbyist Office City", :required=> false},
      {:name => "Lobbyist Office State", :required=> false},
      {:name => "Lobbyist Office Zip", :required=> false},
      {:name => "Lobbyist Office Phone", :required=> false},
      {:name => "Lobbyist Residence Address", :required=> false},
      {:name => "Lobbyist Residence City", :required=> false},
      {:name => "Lobbyist Residence State", :required=> false},
      {:name => "Lobbyist Residence Zip", :required=> false},
      {:name => "Lobbyist Residence Phone", :required=> false},
      {:name => "Principal ID", :required=> false},
      {:name => "Principal Name", :required=> false},
      {:name => "Principal Office Address", :required=> false},
      {:name => "Principal Office City", :required=> false},
      {:name => "Principal Office State", :required=> false},
      {:name => "Principal Office Zip", :required=> false},
      {:name => "Principal Office Phone", :required=> false},
      {:name => "Principal Official Contact", :required=> false},
      {:name => "Principal Nature of Business", :required=> false}