{:name => "Committee Name", :required=> false},
{:name => "Committee ID", :required=> false},
{:name => "Date Received", :required=> false},
{:name => "Contributor ID", :required=> false},
{:name => "Contribution Date", :required=> false},
{:name => "Amount", :required=> false},
{:name => "Nature Of Contribution", :required=> false},
{:name => "Support/Oppose", :required=> false},
{:name => "Description", :required=> false},
{:name => "Microfilm Number", :required=> false},
{:name => "Contributor Name", :required=> false}