      {:name => "Committee ID Number", :required=> false},
      {:name => "Committee Name", :required=> false},
      {:name => "Committee Address", :required=> false},
      {:name => "Committee City", :required=> false},
      {:name => "Committee State", :required=> false},
      {:name => "Committee Zip", :required=> false},
      {:name => "Committee Type", :required=> false},
      {:name => "Date Received", :required=> false},
      {:name => "Postmark Date", :required=> false},
      {:name => "Nature Of Filing", :required=> false},
      {:name => "Ballot Question", :required=> false},
      {:name => "Oppose Ballot Question", :required=> false},
      {:name => "Ballot Type", :required=> false},
      {:name => "Date over Theshold", :required=> false},
      {:name => "Acronym", :required=> false},
      {:name => "Separate Seg Political Fund ID", :required=> false},
      {:name => "Separate Segregated Political Fund Name", :required=> false},
      {:name => "SSPF Address", :required=> false},
      {:name => "SSPF City", :required=> false},
      {:name => "SSPF State", :required=> false},
      {:name => "SSPF Zip", :required=> false},
      {:name => "SSPF Type", :required=> false},
      {:name => "Date Dissolved", :required=> false},
      {:name => "Date of Next Election", :required=> false},
      {:name => "Election Type", :required=> false},
      {:name => "Won General", :required=> false},
      {:name => "Won Primary", :required=> false}